name: Caller1

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 環境はどこ？
        type: choice
        options:
          - aws
          - aws2
          - aws3
      release:
        required: true
        description: リリース有無
        type: boolean
        default: false

jobs:
  call_workflow:
    if: ${{github.event.inputs.release == true}}
    uses: ./.github/workflows/called.yml
    with:
      username: ${{github.event.inputs.release}}
