name: ChangeVersion

on:
  workflow_dispatch:
    inputs:
      major-version:
        type: string
        required: true
        description: 'メジャーバージョン（X.-.-）'
      minor-version:
        type: string
        required: true
        description: 'マイナーバージョン（-.X.-）'
      patch-version:
        type: string
        required: true
        description: 'パッチバージョン（-.-.X）'
      bundle-version:
        type: string
        default: '0'
        required: false
        description: 'バンドルバージョン（-.-.-.X）'

jobs:
  changeVersion:
    runs-on: ubuntu-latest
    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v2
        with:
          ref: master
      # バージョンを設定、更新
      - name: change version
        run: |
          echo "VERSION=${{ github.event.inputs.major-version }}.${{ github.event.inputs.minor-version }}.${{ github.event.inputs.patch-version }}.${{ github.event.inputs.bundle-version }}" >> $GITHUB_ENV
          sed -i"" -e "s|\'VERSION\':\ \'[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\'|\'VERSION\':\ \'$APP_VERSION\'|" version.js
        shell: bash

      ## 更新をcommit, push
      - name: Git commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.js && \
            git commit -m "バージョンを更新" --no-verify && \
            git push --set-upstream origin master
