name: Go Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v2
      # Go環境のセットアップ
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      # テストの実行
      - name: Test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v2
      # イメージビルドにBuildKitを有効化
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # イメージのビルドとpush
      - name: Build and push Docker image
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][¥.].*")
          DOCKER_IMAGE=${{secret.DOCKER_USERNAME}}/greeting:$TAG
          docker login --username ${{secret.DOCKER_USERNAME}} --password ${{secret.DOCKER_PASSWORD}}
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
